return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.8.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 69,
  height = 5000,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 5,
  nextobjectid = 104,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "asteroids",
      visible = true,
      opacity = 1,
      offsetx = 21.784,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 237, 51, 59 },
      properties = {},
      objects = {
        {
          id = 64,
          name = "",
          type = "",
          shape = "ellipse",
          x = 352,
          y = 158400,
          width = 160,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "ellipse",
          x = 2048,
          y = 157440,
          width = 224,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "ellipse",
          x = 192,
          y = 157920,
          width = 256,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "ellipse",
          x = 256,
          y = 158528,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 158336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 158240,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "ellipse",
          x = 160,
          y = 158176,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1408,
          y = 157312,
          width = 248.739,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1248,
          y = 155680,
          width = 224,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "ellipse",
          x = 160,
          y = 158208,
          width = 224,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "ellipse",
          x = 992,
          y = 157344,
          width = 266.216,
          height = 245.938,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "ellipse",
          x = 288,
          y = 157152,
          width = 224,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "ellipse",
          x = 544,
          y = 158144,
          width = 224,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 157728,
          width = 224,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1600,
          y = 158080,
          width = 224,
          height = 224,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "ellipse",
          x = 896,
          y = 157824,
          width = 554.216,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1600,
          y = 157851,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1632,
          y = 157696,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1440,
          y = 158304,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1024,
          y = 158432,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "ellipse",
          x = 768,
          y = 157920,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1280,
          y = 158432,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1856,
          y = 158080,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1760,
          y = 158496,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1888,
          y = 158304,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1824,
          y = 157856,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1472,
          y = 157728,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "ellipse",
          x = 896,
          y = 157696,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "ellipse",
          x = 1344,
          y = 157760,
          width = 74.216,
          height = 68.5628,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Custom Objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 38, 162, 105 },
      properties = {},
      objects = {
        {
          id = 79,
          name = "",
          type = "",
          shape = "ellipse",
          x = 320,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = false,
          properties = {}
        },
        {
          id = 103,
          name = "Player Start",
          type = "",
          shape = "ellipse",
          x = 1184,
          y = 159936,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["player_start"] = true
          }
        }
      }
    }
  }
}
