return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.8.0",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 69,
  height = 500,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 8,
  nextobjectid = 237,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "Custom Game Objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 192,
          name = "Player",
          type = "Player",
          shape = "rectangle",
          x = 1168,
          y = 15768,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "Food",
          shape = "rectangle",
          x = 1112,
          y = 15496,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "Food",
          shape = "rectangle",
          x = 1144,
          y = 15408,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          type = "Food",
          shape = "rectangle",
          x = 1112,
          y = 15424,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "Food",
          shape = "rectangle",
          x = 1184,
          y = 15432,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "Food",
          shape = "rectangle",
          x = 1256,
          y = 15512,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "Food",
          shape = "rectangle",
          x = 1192,
          y = 15560,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "Food",
          shape = "rectangle",
          x = 1216,
          y = 15440,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Obstacles",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 224, 27, 36 },
      properties = {},
      objects = {
        {
          id = 188,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1088,
          y = 15536,
          width = 41.3701,
          height = 41.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1048,
          y = 15256,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1408,
          y = 15688,
          width = 48,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 984,
          y = 15624,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1208,
          y = 15656,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1272,
          y = 15672,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1104,
          y = 15664,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1352,
          y = 15512,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1240,
          y = 15560,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1264,
          y = 15448,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1088,
          y = 15376,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 944,
          y = 15504,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 984,
          y = 15536,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1184,
          y = 15496,
          width = 41.3701,
          height = 41.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1048,
          y = 15440,
          width = 41.3701,
          height = 41.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1256,
          y = 15344,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1352,
          y = 15280,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1224,
          y = 15240,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1008,
          y = 15392,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1176,
          y = 15360,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "Obstacle",
          shape = "rectangle",
          x = 1152,
          y = 15456,
          width = 17.3518,
          height = 17.3386,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
